USE [QUANLYBANLE]
GO

/* ============================================================
   BO SUNG DATABASE CHO WEBSITE BAN THIET BI DIEN MAY
   Chay sau u.sql. Script idempotent: chi tao bang/cot neu chua co.
   ============================================================ */

IF COL_LENGTH('dbo.SANPHAM', 'HINHANH') IS NULL
    ALTER TABLE dbo.SANPHAM ADD HINHANH NVARCHAR(500) NULL;
GO

IF COL_LENGTH('dbo.SANPHAM', 'THUONGHIEU') IS NULL
    ALTER TABLE dbo.SANPHAM ADD THUONGHIEU NVARCHAR(100) NULL;
GO

IF COL_LENGTH('dbo.SANPHAM', 'THOIGIANBAOHANH') IS NULL
    ALTER TABLE dbo.SANPHAM ADD THOIGIANBAOHANH INT NULL;
GO

IF COL_LENGTH('dbo.KHUYENMAI', 'PHANTRAMGIAM') IS NULL
    ALTER TABLE dbo.KHUYENMAI ADD PHANTRAMGIAM FLOAT NULL DEFAULT (0);
GO

IF COL_LENGTH('dbo.KHUYENMAI', 'SOTIENGIAM') IS NULL
    ALTER TABLE dbo.KHUYENMAI ADD SOTIENGIAM FLOAT NULL DEFAULT (0);
GO

IF OBJECT_ID('dbo.THONGSOSANPHAM', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.THONGSOSANPHAM(
        MATHONGSO CHAR(15) NOT NULL,
        MASP CHAR(15) NOT NULL,
        TENTHONGSO NVARCHAR(200) NULL,
        GIATRI NVARCHAR(500) NULL,
        PRIMARY KEY CLUSTERED (MATHONGSO ASC),
        CONSTRAINT FK_THONGSOSANPHAM_SANPHAM FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP)
    );
END
GO

IF OBJECT_ID('dbo.GIOHANG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.GIOHANG(
        MAGIOHANG CHAR(15) NOT NULL,
        MAKH CHAR(15) NOT NULL,
        NGAYTAO DATETIME NULL DEFAULT (GETDATE()),
        TRANGTHAI NVARCHAR(50) NULL DEFAULT (N'Dang mo'),
        PRIMARY KEY CLUSTERED (MAGIOHANG ASC),
        CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH)
    );
END
GO

IF OBJECT_ID('dbo.CHITIETGIOHANG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHITIETGIOHANG(
        MAGIOHANG CHAR(15) NOT NULL,
        MASP CHAR(15) NOT NULL,
        SOLUONG INT NULL DEFAULT (1),
        DONGIA FLOAT NULL DEFAULT (0),
        PRIMARY KEY CLUSTERED (MAGIOHANG ASC, MASP ASC),
        CONSTRAINT FK_CHITIETGIOHANG_GIOHANG FOREIGN KEY (MAGIOHANG) REFERENCES dbo.GIOHANG(MAGIOHANG),
        CONSTRAINT FK_CHITIETGIOHANG_SANPHAM FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP),
        CONSTRAINT CK_CHITIETGIOHANG_SOLUONG CHECK (SOLUONG > 0)
    );
END
GO

IF OBJECT_ID('dbo.DONHANG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DONHANG(
        MADONHANG CHAR(15) NOT NULL,
        MAKH CHAR(15) NOT NULL,
        NGAYDAT DATETIME NULL DEFAULT (GETDATE()),
        TONGTIEN FLOAT NULL DEFAULT (0),
        TRANGTHAI NVARCHAR(50) NULL DEFAULT (N'Cho xac nhan'),
        GHICHU NVARCHAR(500) NULL,
        PRIMARY KEY CLUSTERED (MADONHANG ASC),
        CONSTRAINT FK_DONHANG_KHACHHANG FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH)
    );
END
GO

IF OBJECT_ID('dbo.CHITIETDONHANG', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHITIETDONHANG(
        MADONHANG CHAR(15) NOT NULL,
        MASP CHAR(15) NOT NULL,
        SOLUONG INT NULL DEFAULT (1),
        DONGIA FLOAT NULL DEFAULT (0),
        TONGTIEN FLOAT NULL DEFAULT (0),
        PRIMARY KEY CLUSTERED (MADONHANG ASC, MASP ASC),
        CONSTRAINT FK_CHITIETDONHANG_DONHANG FOREIGN KEY (MADONHANG) REFERENCES dbo.DONHANG(MADONHANG),
        CONSTRAINT FK_CHITIETDONHANG_SANPHAM FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP),
        CONSTRAINT CK_CHITIETDONHANG_SOLUONG CHECK (SOLUONG > 0)
    );
END
GO

IF OBJECT_ID('dbo.VANCHUYEN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.VANCHUYEN(
        MAVANCHUYEN CHAR(15) NOT NULL,
        MADONHANG CHAR(15) NOT NULL,
        DONVIVANCHUYEN NVARCHAR(100) NULL,
        MAVANDON NVARCHAR(100) NULL,
        DIACHIGIAO NVARCHAR(500) NULL,
        PHIVANCHUYEN FLOAT NULL DEFAULT (0),
        TRANGTHAI NVARCHAR(50) NULL DEFAULT (N'Cho giao'),
        NGAYGIAO_DUKIEN DATETIME NULL,
        NGAYGIAO_THUCTE DATETIME NULL,
        PRIMARY KEY CLUSTERED (MAVANCHUYEN ASC),
        CONSTRAINT FK_VANCHUYEN_DONHANG FOREIGN KEY (MADONHANG) REFERENCES dbo.DONHANG(MADONHANG)
    );
END
GO

IF OBJECT_ID('dbo.BAOHANH', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.BAOHANH(
        MABAOHANH CHAR(15) NOT NULL,
        MASP CHAR(15) NOT NULL,
        MAKH CHAR(15) NULL,
        MAHDBAN CHAR(15) NULL,
        NGAYBATDAU DATE NULL,
        NGAYKETTHUC DATE NULL,
        TRANGTHAI NVARCHAR(50) NULL DEFAULT (N'Con bao hanh'),
        GHICHU NVARCHAR(500) NULL,
        PRIMARY KEY CLUSTERED (MABAOHANH ASC),
        CONSTRAINT FK_BAOHANH_SANPHAM FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP),
        CONSTRAINT FK_BAOHANH_KHACHHANG FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH),
        CONSTRAINT FK_BAOHANH_HOADONBAN FOREIGN KEY (MAHDBAN) REFERENCES dbo.HOADONBAN(MAHDBAN),
        CONSTRAINT CK_BAOHANH_DATE CHECK (NGAYKETTHUC IS NULL OR NGAYBATDAU IS NULL OR NGAYKETTHUC >= NGAYBATDAU)
    );
END
GO

IF OBJECT_ID('dbo.DOITRA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DOITRA(
        MADOITRA CHAR(15) NOT NULL,
        MAHDBAN CHAR(15) NOT NULL,
        MASP CHAR(15) NOT NULL,
        MAKH CHAR(15) NULL,
        SOLUONG INT NULL DEFAULT (1),
        LYDO NVARCHAR(500) NULL,
        HINHTHUC NVARCHAR(50) NULL,
        GIATRI FLOAT NULL DEFAULT (0),
        NGAYTAO DATETIME NULL DEFAULT (GETDATE()),
        TRANGTHAI NVARCHAR(50) NULL DEFAULT (N'Cho xu ly'),
        PRIMARY KEY CLUSTERED (MADOITRA ASC),
        CONSTRAINT FK_DOITRA_HOADONBAN FOREIGN KEY (MAHDBAN) REFERENCES dbo.HOADONBAN(MAHDBAN),
        CONSTRAINT FK_DOITRA_SANPHAM FOREIGN KEY (MASP) REFERENCES dbo.SANPHAM(MASP),
        CONSTRAINT FK_DOITRA_KHACHHANG FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(MAKH),
        CONSTRAINT CK_DOITRA_SOLUONG CHECK (SOLUONG > 0)
    );
END
GO

CREATE OR ALTER VIEW dbo.V_DONHANG_CHITIET AS
SELECT dh.MADONHANG,
       dh.MAKH,
       kh.TENKH,
       dh.NGAYDAT,
       dh.TRANGTHAI AS TRANGTHAI_DONHANG,
       ct.MASP,
       sp.TENSP,
       ct.SOLUONG,
       ct.DONGIA,
       ct.TONGTIEN
FROM dbo.DONHANG dh
LEFT JOIN dbo.KHACHHANG kh ON kh.MAKH = dh.MAKH
LEFT JOIN dbo.CHITIETDONHANG ct ON ct.MADONHANG = dh.MADONHANG
LEFT JOIN dbo.SANPHAM sp ON sp.MASP = ct.MASP;
GO

CREATE OR ALTER PROC dbo.SP_THEMDONHANG
    @MADONHANG CHAR(15),
    @MAKH CHAR(15),
    @GHICHU NVARCHAR(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM dbo.DONHANG WHERE MADONHANG = @MADONHANG)
        RETURN -1;
    INSERT INTO dbo.DONHANG(MADONHANG, MAKH, NGAYDAT, TONGTIEN, TRANGTHAI, GHICHU)
    VALUES(@MADONHANG, @MAKH, GETDATE(), 0, N'Cho xac nhan', @GHICHU);
END
GO

CREATE OR ALTER PROC dbo.SP_THEMCHITIETDONHANG
    @MADONHANG CHAR(15),
    @MASP CHAR(15),
    @SOLUONG INT,
    @DONGIA FLOAT
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM dbo.CHITIETDONHANG WHERE MADONHANG = @MADONHANG AND MASP = @MASP)
        RETURN -1;

    INSERT INTO dbo.CHITIETDONHANG(MADONHANG, MASP, SOLUONG, DONGIA, TONGTIEN)
    VALUES(@MADONHANG, @MASP, @SOLUONG, @DONGIA, @SOLUONG * @DONGIA);

    UPDATE dbo.DONHANG
    SET TONGTIEN = (
        SELECT SUM(ISNULL(TONGTIEN, 0))
        FROM dbo.CHITIETDONHANG
        WHERE MADONHANG = @MADONHANG
    )
    WHERE MADONHANG = @MADONHANG;
END
GO

CREATE OR ALTER PROC dbo.SP_XACNHANDONHANG
    @MADONHANG CHAR(15)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE dbo.DONHANG
    SET TRANGTHAI = N'Da xac nhan'
    WHERE MADONHANG = @MADONHANG;
END
GO

CREATE OR ALTER PROC dbo.SP_HUYDONHANG
    @MADONHANG CHAR(15)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE dbo.DONHANG
    SET TRANGTHAI = N'Da huy'
    WHERE MADONHANG = @MADONHANG;
END
GO
